"""Initial migration

Revision ID: 24b7dedef20c
Revises: 
Create Date: 2026-04-01 03:25:35.667449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24b7dedef20c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'MEMBER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_user_email', ['email'], unique=False)

    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index('idx_team_created_by', ['created_by'], unique=False)

    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'user_id', name='unique_team_user')
    )
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.create_index('idx_team_members_team_id', ['team_id'], unique=False)
        batch_op.create_index('idx_team_members_user_id', ['user_id'], unique=False)

    op.create_table('workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.create_index('idx_workflow_team_id', ['team_id'], unique=False)

    op.create_table('workflow_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_stages', schema=None) as batch_op:
        batch_op.create_index('idx_workflow_stages_order', ['workflow_id', 'order_index'], unique=False)
        batch_op.create_index('idx_workflow_stages_workflow_id', ['workflow_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('workflow_stage_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='taskpriority'), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workflow_stage_id'], ['workflow_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index('idx_task_assigned_to', ['assigned_to'], unique=False)
        batch_op.create_index('idx_task_deadline', ['deadline'], unique=False)
        batch_op.create_index('idx_task_priority', ['priority'], unique=False)
        batch_op.create_index('idx_task_workflow_stage_id', ['workflow_stage_id'], unique=False)

    op.create_table('task_activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('performed_by', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_activity_logs', schema=None) as batch_op:
        batch_op.create_index('idx_activity_log_performed_by', ['performed_by'], unique=False)
        batch_op.create_index('idx_activity_log_task_id', ['task_id'], unique=False)
        batch_op.create_index('idx_activity_log_timestamp', ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_activity_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_activity_log_timestamp')
        batch_op.drop_index('idx_activity_log_task_id')
        batch_op.drop_index('idx_activity_log_performed_by')

    op.drop_table('task_activity_logs')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('idx_task_workflow_stage_id')
        batch_op.drop_index('idx_task_priority')
        batch_op.drop_index('idx_task_deadline')
        batch_op.drop_index('idx_task_assigned_to')

    op.drop_table('tasks')
    with op.batch_alter_table('workflow_stages', schema=None) as batch_op:
        batch_op.drop_index('idx_workflow_stages_workflow_id')
        batch_op.drop_index('idx_workflow_stages_order')

    op.drop_table('workflow_stages')
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_index('idx_workflow_team_id')

    op.drop_table('workflows')
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_index('idx_team_members_user_id')
        batch_op.drop_index('idx_team_members_team_id')

    op.drop_table('team_members')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index('idx_team_created_by')

    op.drop_table('teams')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_user_email')

    op.drop_table('users')
    # ### end Alembic commands ###
