"""Add user_id to tasks

Revision ID: cbc5a4285aca
Revises: 24b7dedef20c
Create Date: 2026-04-01 03:38:36.402022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbc5a4285aca'
down_revision = '24b7dedef20c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index('idx_task_user_id', ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_tasks_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_user_id', type_='foreignkey')
        batch_op.drop_index('idx_task_user_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
